# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ecf30db8abda1599cf4b14b963e1625bcd80a4cc48f50f2b3138bcb37e9c0367ccae31fc69221d301b87ec6ec0b67c027e4d51bec15e759b9a014d7f24af47dd

test:
  secret_key_base: bdb1d44f520507439a732b53e2ca4f7d047e8ea5f2b48e7942c6d421ebc1f1cd48f9d29b53f13af030ccd2341c53603b49baa02c36afadd281223ad0254e67cc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
